### PR TITLE
updated chapter 2

### PR DESCRIPTION
**Pull request by annahutch**
I have updated chapter 2, including adding instructions for mac users. Any feedback appreciated!!

### CODE REVIEW

**Comment by annahutch** [comment]
Haha yes, that ideas doc is not supposed to be in there.. should i remove then re-commit/ re-push?

**Comment by kkmann** [comment]
yo, important note though - since you already pushed the file, it will remain in the history of the repository (that's why it is a bad idea to accidentally commit passwords!) doesn't matter to me, and you can just delete/add/commit/push again. 
In general, deleting files from history is a pain: https://blog.ostermiller.org/git-remove-from-history.
Since you did not merge with master yet, you could still do a 'Squash and merge' instead of a 'Create a merge commit' - since this will combine all commits in one and your new commit doe not conaint the file anymore it will not end up in the history of master. You should just make sure to delete this feature branch after merging!

So, first, delte the file locally, add, commit, push, then we can approve the pull request and you can do the squas + merge ;)

PS: and yes you do 'git add' even though you deleted a file ...

**Comment by kkmann** [comment]
remember to use 'squash and merge' and to delete the branch after merging then your docx will be gone ;)

**Comment by annahutch** [comment]
Think I've done it!

**Pull request merged**
