### PR TITLE
Ci and build automation

### PR DESCRIPTION
**Pull request by magnusmunch**
I added an example project

### CODE REVIEW

**Comment by kkmann** [comment]
Ha, cool stuff - we were just discussing workflow diagrams today! You must be a mentalist ;)
I think it would be much easier if you just included the plotting code in the chapter .Rmd. if you want to keep it separate, you should probably source it (and we need to add a scripts/ folder for storing these kinds of stuff).
There is no need to save the .png itself when the plot is invoked from the markdown file.

**Comment by magnusmunch** [comment]
Well, I created a Code folder that contains an r script and I'm using read_chunk() to source it. That's basically the same thing as actually using source() right?

**Comment by kkmann** [comment]
sounds even more sophisticated - still, why not just put in the .Rmd? It's not thaaaaaat long ;) KISS principle... 
I also don't really get the point of using read_chunk() - it's not executing the code according to the docs, right? So, I am happy to use source() if you feel that the code is too long/ugly for the .Rmd but I just don't see the point of read_chunk().

**Comment by magnusmunch** [comment]
True, we could use source as well. I personally use it because I keep one R file with all my figure code and give each figure generating code its own header. With read_chunk() you then execute the one figure generating code part you need in a specific code chunk in your Rmd file. In that way you don't have to have separate R files that you source for each created figure.

Also, it's useful if you recreate the same figure in more than one document or chapter. You can just execute the same figure generating part again using read_chunck() and the specific header. Although you could use source for that as well, but that still leaves you with the different R files for different figures.

**Comment by kkmann** [comment]
looks like I missed you by a sec ;) Okay, pretty weird stuff - thanks for bringing this up. never seen it before. Would probably be a good addition to our literate programming chapter as well ;)
So, you read section of your .R file by label and then just put an empty chunk with the corresponding label in your .Rmd. 
I do find it a bit weird since you kinda need to be a knitr expert to figure out where to find the actual code. I am happy to back this if you insist but would strongly recommend to just put the figure code in the .Rmd for simplicities sake. 

One more thing - how come this builds without error? You introduce diagram as new package dependency but you do not declare it in the DESCRIPTION file. ... ah okay - the build script somehow misses throwing an error, I'll fix it...

**Comment by kkmann** [comment]
okay, let's see whether it works. We should now get a build error due to the missing dependency. Just add it to the depends field in the DESCRIPTION file and it should work again ;)

**Comment by magnusmunch** [comment]
I have split continuous integration and build automation into two chapters, following Kevin in the containerisation branch

**Pull request merged**
