### PR TITLE
Python chapter

### PR DESCRIPTION
**Pull request by alexanderbuchholz**
I started working on an example for python packages and unit testing. This is a preliminary version.

### CODE REVIEW

**Comment by kkmann** [comment]
hey @alexanderbuchholz, I think we'd prefer to keep example repositories separate from the core book. simple reason: anybody interested in following the examples along can just git clone the respective example repository. Would you be willing to move you example to a new repo in rr-mrc-bsu? So, if I overlooked everythink correctly we'd only need to change the .Rmd in this repo.

**Comment by kkmann** [comment]
cf. https://github.com/rr-mrc-bsu/containerization-example

**Comment by alexanderbuchholz** [comment]
Hey @kkmann, ok I will do so!

**Comment by kkmann** [comment]
closing this now, feel free to reopen though!

**Pull request closed without merging**
